library("XLConnect")
setwd("D:/Program Files/TableCreator by ForYou")
source("CreatingTableCreator11.R")
setwd("D:/Program Files/TableCreator by ForYou")
source("CreatingTableCreator12.R")
setwd("D:/Program Files/TableCreator by ForYou")
source("CreatingTableCreator13.R")
setwd("D:/Program Files/TableCreator by ForYou/output_documents")
date <- paste(as.character(date()),".txt",sep="")
date <- gsub(" ","_",date)
date <- gsub(":","-",date)
fileDate<-file(date)
writeLines("Information", fileDate)
close(fileDate)